sudo: required
language: generic
matrix:
  include:
    # Use generic language for osx
    - os: osx
      osx_image: xcode8.3
      language: generic    
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86   
    - os: osx
      osx_image: xcode8.3
      language: generic   
      env: 
        - BUILD_CONFIG=debug 
        - BUILD_ARCHITECTURE=x86
    - os: osx
      osx_image: xcode8.3
      language: generic   
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86_64
    - os: osx
      osx_image: xcode8.3
      language: generic   
      env: 
        - BUILD_CONFIG=debug 
        - BUILD_ARCHITECTURE=x86_64
    # Use the built in venv for linux builds
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=debug 
        - BUILD_ARCHITECTURE=x86
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86_64
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=coverage 
        - BUILD_ARCHITECTURE=x86_64
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=debug 
        - BUILD_ARCHITECTURE=x86_64
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86_64
        - GCC_VERSION=5
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=release 
        - BUILD_ARCHITECTURE=x86_64
        - GCC_VERSION=6
    - os: linux
      dist: trusty
      env: 
        - BUILD_CONFIG=zpm
        - GCC_VERSION=6
global:
  env:
    - PROJECT=CoreLib
    - PROJECT_DIRECTORY=core
install:
  - source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
  - zpm run build-ci-library
after_success:
  - zpm run deploy-ci-library 
notifications:
  slack: 
    secure: "ci9IliOCS5ylvvAjVx2rvZPNl/o1eV2EzyNbv+1IbbG8XFJs1iFofi6Bvbs00FhSSIrpfgLSbXkVR+fMAEge6Z/cjAXveOHkzx9gsKZzKtHrsEHgmndT0EYzBHDHOua/cggnB7TEanDA97JOQCfN6sOYymHSFYWY+B/Il5iCMuPKVLKISFbCZ/3Urxh0Gn7O0bkxQ5wy5IQ5c5Bx5zGj8MxQOrvOcuLkYHCC3mH40e1yfTdEdZB9Yuf9HcTIh1lLY5kk9Xt+88v2ag/vUSY0bAq3Ewg00mXReedFm3nqBqZ+PT/HYgK4zMo2yuPZ1RXWIZCykP65Sbms3dygfDnf98SywlYkXFlLaDFryiz0qQXBzCG/DZ8OoFOfO7NSjxIyDy/gmTeTm74ytc/wZVh4IDgYuhR/eSA7ZgAXReBnUVQSimbf3Y4WD3cHNx4f9U6QyJZFhjJLRzlyN7N/kPGMb7fSbpHUr9T3nFQ0ixygEhmQIJEMhVDSLLdDNFqlMCC2VdzieShr0Ml5s1L+2km9cPOzuNPGMR+PjyBq7mmEdXrv15qQu7+iKltUsJlsjmGLTxUytM83h4Orjl6sLdEmtDxr/0MWfCVp643j+3nv5bHo5LkXfJU9DnH4pLLFyeZnyjpxe0jHiIfe8OMv8gV+MxU501Wfo+PKKCq6elK2JtM="