sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode9.2
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=6
global:
  env:
  - PROJECT=CoreLib
  - PROJECT_DIRECTORY=core
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: TWijsoFU5A220ya64vPYKuLuthcOz2Ybe4XSWJ5fDQUYv4YVOZVf588o7031RB6Im9sxxWhD0qykyQWZZugAwEjaLYbnCnNjx9k7KoF0IUs2nniD/oUrYgwO4o6o88FwF/z/+uuewteIGYbzVXWEsgzDcoU98f16J/0xCHpYsDVZamvnN0RQpAw9jDRQvK6k5LTz05jNO4xG1C5RwdP5dc/qzxMfGgDOqJzQRCkNZiqtcvyoFMH7lskhOCOcxCFk7P+jb832H0+JWcDH9HNP0d6EefORSLsmP4u9q8rIALuZb7VrZnu8+PdgUTP5BPduXnaaNs0iLxPvGWrN05hD5Y9jrq6pH2/RjPcLqdNWY0tuI1oxDuNh6AbAY02m+6H0JMJaWMOTIggha/mFLYojxVhvqUlqyo6uOtu+i6+YIUgZMDAARKPTc9rd7hRZNUWLxZA0bkMlsIA+QC08PpbBE+/Kbu5Rr4Ei3e+1EJ2I1RJjX3ZujCMTD/WJWXO9gTU5wQG0HNCzcR4I4vaXNpz6cuTcYHzmuY7BpW+v/q1xw+F8+0jg9410jeH+lzdp6jFw75cdI85DEkrlIGElKQToSqAO/hDjruXfOWk2usKOUHNYn1ViDNKVlyuHVFWUqyiMa/xF2w2LqgDIhXY+0yMEwQgfvKp+K9JqVOppAqrts94=
