sudo: required
language: generic
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty
          env: TYPE=release ARCH=x86
        - os: linux
          dist: trusty
          env: TYPE=debug ARCH=x86
        - os: linux
          dist: trusty
          env: TYPE=release ARCH=x86_64
        - os: linux
          dist: trusty
          env: TYPE=coverage ARCH=x86_64
        - os: linux
          dist: trusty
          env: TYPE=debug ARCH=x86_64
        - os: linux
          dist: trusty
          env: TYPE=zpm
        # Use generic language for osx
        # disabled due to premake bug
        - os: osx
          osx_image: xcode8
          language: generic    
          env: TYPE=release ARCH=x86   
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=debug ARCH=x86
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=release ARCH=x86_64
        - os: osx
          osx_image: xcode8
          language: generic   
          env: TYPE=debug ARCH=x86_64

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -y
    - sudo apt-get install gcc-6 g++-6 -y
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 60
    - sudo update-alternatives --config gcc
    - sudo update-alternatives --config g++
    - sudo apt-get install gcc-6-multilib g++-6-multilib
install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install codecov; fi
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
script:
    - bash script/travis-build.sh
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TYPE" = "coverage" ]]; then codecov; fi    