sudo: required
language: generic
matrix:
  include:
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
  - os: osx
    osx_image: xcode8.3
    language: generic
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=coverage
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=7
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=6
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=debug
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86_64
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=release
    - BUILD_ARCHITECTURE=x86
    - GCC_VERSION=5
  - os: linux
    dist: trusty
    env:
    - BUILD_CONFIG=zpm
    - GCC_VERSION=5
global:
  env:
  - PROJECT=CoreLib
  - PROJECT_DIRECTORY=core
install:
- source /dev/stdin <<< "$(curl -s https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.sh)"
script:
- zpm run build-ci-library
after_success:
- zpm run deploy-ci-library
notifications:
  slack:
    secure: nBTt7CgsVqbBTiDDmAmw/ScfzkVqRcRCfeO5/YY3hyVcR2qRN1oUzboFuxKYq0/OnQnqNyKO8xxQORGtPz44mqE7J6rF1bAKaCCLADPFKcOvRdlIrBfbKnBKZco1BuKODRFo3/+E+Kip515NiBK6O4aFACtvVtesSgRIcmPQ35tBqtXmHXP7537X2anRGssgtu7ePKrT4VOxdKRNvv6FvTGOWqwcIai7KL6NobgJPp7WcfMsiQMXNIezvryctqUN5WrdYrejnxbBSJG/6QRFC8bcpWlUFbid0Z3lm/eRKzZSMp2ALCkJOJqy7fmp0QFw03FKwhA7hI6A/0nam57kPOhf+tTPOMgBmmKhU19YdJobgPFbLLcHZ6EvaPlnIY1ZAUNvic+GeMt/4Nh7a4bs2JHGUcus/C1/AeNDRen2AgV1s9Cff2ZjiJRdyBMF/I2/oscspnKB2ruiN2mSmwlb2YqINf9jQcJOFjAJLoOu5fHDGhotquvRmt5ZufDKIjGlQaaj5ksKMdjWSznreHsTNKiLGaIx54auvj5oVwjHhTQqm6KYqcu8DrnzAvUanDFIkeb0D3+TT661pMhGRaiiQYAeO2odV8H+lxVBFh/pCzq2EPVFehHkuBQF/2Nb8PlJy5mtGDHGrRGWm8/VKkYgpm+wSHqdtEg5y8DMytV6f9g=
