version: '2'
services:

    applications:
        image: tianon/true
        volumes:
            - .:/app/

    workspace:
        build:
            context: ./docker/
            args:
                - INSTALL_WORKSPACE_SSH=true
        volumes_from:
            - applications
        tty: true